# -*- coding: utf-8 -*-
"""00_HelloWord.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-MZTzqdV5xdw2msnLvM1fMeUMETTt9Aj
"""

# Este simbolo se utilza para comentar el codigo.
print("Hola grupo 230 de la carrera de tecnica de PROGRAMACION")
#Como consultar el tipo de dato
print(type("Soy un dato str"))   # Tipo 'str'
print(type(5))  # Tipo 'int'
print(type(1.5))  # Tipo 'float'
print(type(3 + 1j))  #Tipo 'complex'
print(type(True))  # Tipo 'bool'
print(type(print("Mi cadena de texto")))  # Tipo 'NoneTipe'